# fly.toml app configuration file generated for kuryart-portfolio on 2023-11-30T00:50:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kuryart-portfolio"
primary_region = "gru"

[build]

[env]
  LOG_LEVEL = "debug"
  NODE_ENV = "development"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
