name: Bun with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: ${{ matrix.node-version }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1.1.0    

    - name: Build
      run: |
        bun install
        bun run gulp
        bun run src/main.ts
      env: 
        NODE_ENV: ${{ vars.NODE_ENV }}
        LOG_LEVEL: ${{ vars.LOG_LEVEL }}
