name: Bun with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages

    # strategy:
    #   matrix:
    #     node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: ${{ matrix.node-version }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1.1.0    

    - name: Build
      env: 
        NODE_ENV: ${{ vars.NODE_ENV }}
        LOG_LEVEL: ${{ vars.LOG_LEVEL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      run: |
        bun install
        bun run gulp
        bun run build
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        bunx gh-pages -d public/dist -u "github-actions-bot <support+actions@github.com>"
    
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public/dist # The folder the action should deploy.